name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches: [custom]

jobs:
  build-android:
    name: Build Android Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.1'
          channel: 'stable'

      - name: Generate translations loader
        working-directory: mobile
        run: dart run easy_localization:generate -S ../i18n

      - name: Generate translations keys
        working-directory: mobile
        run: dart run bin/generate_keys.dart

      - name: Run build_runner
        working-directory: mobile
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Format generated files
        working-directory: mobile
        run: dart format lib/generated/

      - name: Build APK
        working-directory: mobile
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: immich-tk-debug-apk
          path: mobile/build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7
